export interface IconDef {
  file: string;
  name: string;
  category: string;
}

export const ICONS: IconDef[] = [
  // Action
  { file: 'btn_icon-1.svg',   name: 'edit',               category: 'Action' },
  { file: 'btn_icon-2.svg',   name: 'delete',             category: 'Action' },
  { file: 'btn_icon-3.svg',   name: 'duplicate',          category: 'Action' },
  { file: 'btn_icon-4.svg',   name: 'copy',               category: 'Action' },
  { file: 'btn_icon-13.svg',  name: 'send',               category: 'Action' },
  { file: 'btn_icon-29.svg',  name: 'undo',               category: 'Action' },
  { file: 'btn_icon-70.svg',  name: 'share',              category: 'Action' },
  { file: 'btn_icon-72.svg',  name: 'share-check',        category: 'Action' },
  { file: 'btn_icon-52.svg',  name: 'edit-upload',        category: 'Action' },
  { file: 'btn_icon-49.svg',  name: 'link',               category: 'Action' },
  { file: 'btn_icon-66.svg',  name: 'link-handshake',     category: 'Action' },
  { file: 'btn_icon-89.svg',  name: 'filter',             category: 'Action' },

  // File
  { file: 'btn_icon-7.svg',   name: 'download',           category: 'File' },
  { file: 'btn_icon-14.svg',  name: 'cloud-download',     category: 'File' },
  { file: 'btn_icon-15.svg',  name: 'archive',            category: 'File' },
  { file: 'btn_icon-30.svg',  name: 'file-check',         category: 'File' },
  { file: 'btn_icon-31.svg',  name: 'file-plus',          category: 'File' },
  { file: 'btn_icon-32.svg',  name: 'file-x',             category: 'File' },
  { file: 'btn_icon-33.svg',  name: 'file-logout',        category: 'File' },
  { file: 'btn_icon-44.svg',  name: 'file-upload',        category: 'File' },
  { file: 'btn_icon-45.svg',  name: 'file-download',      category: 'File' },
  { file: 'btn_icon-50.svg',  name: 'file-search',        category: 'File' },
  { file: 'btn_icon-55.svg',  name: 'file-clock',         category: 'File' },
  { file: 'btn_icon-57.svg',  name: 'folder-open',        category: 'File' },
  { file: 'btn_icon-58.svg',  name: 'folder',             category: 'File' },
  { file: 'btn_icon-59.svg',  name: 'file',               category: 'File' },
  { file: 'btn_icon-64.svg',  name: 'folder-closed',      category: 'File' },
  { file: 'btn_icon-83.svg',  name: 'file-text-edit',     category: 'File' },
  { file: 'btn_icon-85.svg',  name: 'file-content-edit',  category: 'File' },
  { file: 'btn_icon-86.svg',  name: 'file-doc-check',     category: 'File' },
  { file: 'btn_icon-94.svg',  name: 'file-notification',  category: 'File' },
  { file: 'btn_icon-95.svg',  name: 'file-edit-check',    category: 'File' },
  { file: 'file-none_20.svg', name: 'file-none',          category: 'File' },
  { file: 'btn_icon-47.svg',  name: 'download-cloud-arrow', category: 'File' },

  // Navigation & Arrow
  { file: 'btn_icon-21.svg',  name: 'chevron-down',       category: 'Navigation' },
  { file: 'btn_icon-22.svg',  name: 'chevron-left',       category: 'Navigation' },
  { file: 'btn_icon-23.svg',  name: 'chevron-right',      category: 'Navigation' },
  { file: 'btn_icon-24.svg',  name: 'chevron-up',         category: 'Navigation' },
  { file: 'btn_icon-25.svg',  name: 'chevron-up-line',    category: 'Navigation' },
  { file: 'btn_icon-26.svg',  name: 'chevron-left-line',  category: 'Navigation' },
  { file: 'btn_icon-60.svg',  name: 'circle-right-arrow', category: 'Navigation' },
  { file: 'btn_icon-53.svg',  name: 'home-arrow',         category: 'Navigation' },
  { file: 'btn_icon-48.svg',  name: 'home-plus',          category: 'Navigation' },
  { file: 'btn_icon-84.svg',  name: 'image-arrow',        category: 'Navigation' },
  { file: 'icon_20_오른쪽화살표_원.svg', name: 'circle-arrow-right', category: 'Navigation' },
  { file: 'btn_icon-9.svg',   name: 'reload',             category: 'Navigation' },
  { file: '확대_icon.svg',     name: 'expand',             category: 'Navigation' },

  // UI Control
  { file: 'btn_icon-12.svg',  name: 'trash',              category: 'UI Control' },
  { file: 'btn_icon-20.svg',  name: 'minus',              category: 'UI Control' },
  { file: 'btn_icon-28.svg',  name: 'settings',           category: 'UI Control' },
  { file: 'btn_icon-43.svg',  name: 'menu',               category: 'UI Control' },
  { file: 'btn_icon-75.svg',  name: 'more-dots',          category: 'UI Control' },
  { file: 'btn_icon-87.svg',  name: 'settings-check',     category: 'UI Control' },
  { file: 'btn_icon-88.svg',  name: 'settings-sync',      category: 'UI Control' },
  { file: 'btn_icon-90.svg',  name: 'bars-split',         category: 'UI Control' },
  { file: 'btn_icon-96.svg',  name: 'doc-settings-check', category: 'UI Control' },
  { file: 'btn_icon-97.svg',  name: 'settings-check-filled', category: 'UI Control' },
  { file: 'x-01.svg',         name: 'x-large',            category: 'UI Control' },
  { file: 'x-02.svg',         name: 'x-line',             category: 'UI Control' },
  { file: 'x-03.svg',         name: 'x-small',            category: 'UI Control' },
  { file: 'btn-X.svg',        name: 'x-close',            category: 'UI Control' },
  { file: 'btn_check.svg',    name: 'check',              category: 'UI Control' },
  { file: 'btn_icon-81.svg',  name: 'cart-sync',          category: 'UI Control' },

  // Status
  { file: 'btn_icon.svg',     name: 'check-circle',       category: 'Status' },
  { file: 'btn_icon-16.svg',  name: 'x-circle-filled',    category: 'Status' },
  { file: 'btn_icon-17.svg',  name: 'x-circle',           category: 'Status' },
  { file: 'btn_icon-35.svg',  name: 'x-circle-red',       category: 'Status' },
  { file: 'btn_icon-36.svg',  name: 'x-circle-check',     category: 'Status' },
  { file: 'btn_icon-61.svg',  name: 'circle-minus-red',   category: 'Status' },
  { file: 'btn_icon-65.svg',  name: 'x-slash-circle',     category: 'Status' },
  { file: 'btn_icon-71.svg',  name: 'star',               category: 'Status' },
  { file: 'icon_system-3.svg', name: 'check-circle-green', category: 'System' },
  { file: 'icon_system-4.svg', name: 'check-circle-green-lg', category: 'System' },
  { file: 'icon_system-5.svg', name: 'check-circle-green-xl', category: 'System' },
  { file: 'icon_system-6.svg', name: 'help-circle',       category: 'System' },
  { file: 'icon_system-7.svg', name: 'help-circle-lg',    category: 'System' },
  { file: 'icon_system-8.svg', name: 'help-circle-xl',    category: 'System' },
  { file: 'icon_system-9.svg', name: 'warning-triangle',  category: 'System' },
  { file: 'icon_system-10.svg', name: 'warning-triangle-lg', category: 'System' },
  { file: 'icon_system-11.svg', name: 'warning-triangle-xl', category: 'System' },
  { file: 'icon_system-12.svg', name: 'error-circle',     category: 'System' },
  { file: 'icon_system-13.svg', name: 'error-circle-lg',  category: 'System' },
  { file: 'icon_system-14.svg', name: 'error-circle-xl',  category: 'System' },
  { file: 'btn_icon-38.svg',  name: 'circle-filled',      category: 'Status' },
  { file: 'btn_icon-39.svg',  name: 'triangle-filled',    category: 'Status' },

  // Media
  { file: 'btn_icon-18.svg',  name: 'play',               category: 'Media' },
  { file: 'btn_icon-37.svg',  name: 'play-filled',        category: 'Media' },
  { file: 'btn_icon-40.svg',  name: 'eye-off',            category: 'Media' },
  { file: 'btn_icon-41.svg',  name: 'eye',                category: 'Media' },
  { file: 'btn_icon-73.svg',  name: 'microphone',         category: 'Media' },
  { file: 'btn_icon-80.svg',  name: 'image',              category: 'Media' },
  { file: 'btn_icon-92.svg',  name: 'text-waves',         category: 'Media' },
  { file: 'btn_icon-93.svg',  name: 'text-wave-lines',    category: 'Media' },
  { file: 'btn_icon-98.svg',  name: 'volume-speaker',     category: 'Media' },
  { file: 'btn_icon-8.svg',   name: 'headphones',         category: 'Media' },

  // Communication
  { file: 'btn_icon-6.svg',   name: 'mail',               category: 'Communication' },
  { file: 'btn_icon-34.svg',  name: 'mail-forward',       category: 'Communication' },
  { file: 'btn_icon-42.svg',  name: 'chat-filled',        category: 'Communication' },
  { file: 'btn_icon-67.svg',  name: 'phone',              category: 'Communication' },
  { file: 'btn_icon-74.svg',  name: 'user-plus',          category: 'Communication' },
  { file: 'btn_icon-78.svg',  name: 'notification-filled', category: 'Communication' },
  { file: 'btn_icon-79.svg',  name: 'note',               category: 'Communication' },
  { file: 'btn_icon-91.svg',  name: 'mail-notification',  category: 'Communication' },
  { file: 'icon_top.svg',     name: 'bell',               category: 'Communication' },
  { file: 'icon_top-1.svg',   name: 'bell-scroll',        category: 'Communication' },

  // Calendar & Time
  { file: 'btn_icon-46.svg',  name: 'calendar-check',     category: 'Calendar & Time' },
  { file: 'btn_icon-51.svg',  name: 'clock-reset',        category: 'Calendar & Time' },
  { file: 'btn_icon-54.svg',  name: 'clock-check',        category: 'Calendar & Time' },
  { file: 'btn_icon-56.svg',  name: 'credit-card-check',  category: 'Calendar & Time' },
  { file: 'btn_icon-63.svg',  name: 'clock',              category: 'Calendar & Time' },
  { file: 'btn_icon-68.svg',  name: 'clock-list',         category: 'Calendar & Time' },
  { file: 'btn_icon-82.svg',  name: 'calendar-checkmark', category: 'Calendar & Time' },
];

export const CATEGORIES = [...new Set(ICONS.map(i => i.category))];
